# Use the official R image from the R Project
FROM r-base:latest

# Install necessary Linux packages
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install renv
RUN R -e "install.packages('renv', repos='http://cran.rstudio.com/')"

# Set the working directory
WORKDIR /scripts

# Copy the R project files into the Docker image
COPY . .

# Restore the R environment using renv
RUN R -e "renv::restore()"

# Command to run your main script when the container starts
CMD ["Rscript", "main.R"]
